CREATE TABLE notes (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text,
  content text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX search_idx ON notes
USING bm25 (id, title, content)
WITH (key_field='id', text_fields='{"title": {"tokenizer": {"type": "ngram", "min_gram": 1, "max_gram": 5, "prefix_only": false}}, "content": {"tokenizer": {"type": "ngram", "min_gram": 1, "max_gram": 5, "prefix_only": false}}}');

CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
NEW.updated_at = now();
RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_modified_time BEFORE UPDATE ON notes FOR EACH ROW EXECUTE PROCEDURE update_modified_column();
